language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g gulp
install: 
  - npm install
  - bower install
script:
  - gulp ci
notifications:
  email:
    on_success: change
    on_failure: always